Change a lot of code for new functions of ES6
jesuslg123/show-me-the-pass pull request #1
Opened 2018-10-10 16:37 UTC by 0rez91

The button put after the input:password

I hope you like it

2018-10-11 13:37 UTC, jesuslg123 requested changes
Nice job! Please just check the comments before merge.

2018-10-11 13:37 UTC, jesuslg123 commented on .vscode/launch.json
> +    // Use IntelliSense para saber los atributos posibles.
Please remove comments :)

2018-10-11 13:37 UTC, jesuslg123 commented on backup.txt
> +eyIxIjp7IklEIjoxLCJuYW1lIjoiTXkgaWNvbnMgY29sbGVjdGlvbiIsImJvb2ttYXJrX2lkIjoiajV0bTlvcjNuaDAwMDAwMCIsImNyZWF0ZWQiOm51bGwsInVwZGF0ZWQiOjE1MzkyNTc4NzksImFjdGl2ZSI6MSwic291cmNlIjoibG9jYWwiLCJvcmRlciI6MCw
What its this file for? Need to be committed?

2018-10-11 13:37 UTC, jesuslg123 commented on script.js
> -console.log("hi!")
Thx :)

2018-10-24 16:02 UTC, 0rez91 commented
It's time to accept my changes :wink:

2018-10-24 16:24 UTC, jesuslg123 commented on script.js
> +    IMG_UNLOCK = '<img style="height:100%" src="'+getUrlForBrowser('icons/unlock.png')+'">'
Indentation went crazy here xD

2018-10-24 16:29 UTC, 0rez91 commented on script.js
> +    IMG_UNLOCK = '<img style="height:100%" src="'+getUrlForBrowser('icons/unlock.png')+'">'
Solved

2018-10-24 16:29 UTC, 0rez91 commented
Solved the problem

2018-10-25 07:13 UTC, jesuslg123 approved these changes
Awesome work :)

2018-10-25 07:13 UTC, jesuslg123 commented on script.js
> +	var inputs = document.querySelectorAll('input[type="password"]')
Nice change 💯

2018-10-25 07:13 UTC, jesuslg123 commented on script.js
> +        IMG_UNLOCK = '<img style="height:100%" src="'+getUrlForBrowser('icons/unlock.png')+'">'
Now looks deeper than necesary xD IDE is going crazy? Don't worry :P

2018-10-25 07:13 UTC, jesuslg123 commented on script.js
> +	console.log(element_style.paddingTop)
Do we need to log the padding?

2018-10-25 07:27 UTC, merged